### ISSUE TITLE
Read Cohen's book

### ISSUE THREAD

**Issue by kianooshhosseini** [NDCLab/autism-go-academy#2]
Read Cohen's book by the end of December (2 Chapters each week)

- [x] Chapter 1 (on Oct. 5)
- [x] Chapter 2 (on Oct. 10)
- [x] Chapter 3 (on Oct. 10)
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 10
- [x] Chapter 11
- [x] Chapter 12
- [x] Chapter 13
- [x] Chapter 14
- [x] Chapter 15
- [x] Chapter 16
- [x] Chapter 17
- [ ] Chapter 18
- [ ] Chapter 19
- [ ] Chapter 20
- [ ] Chapter 21
- [ ] Chapter 25
- [ ] Chapter 26
- [ ] Chapter 27
- [ ] Chapter 28
- [ ] Chapter 29
- [ ] Chapter 30
- [ ] Chapter 31
